"""Generate deterministic detection-validation coverage artifacts."""

import argparse
import json
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from config import config
from src.correlator import CORRELATION_RULES
from src.network_monitor import NIDS_RULES
from src.rules import load_rules
from src.scenario_manifest import load_scenario_manifests
from src.sigma import load_sigma_rules
from tools.replay_scenario import replay_path


ROOT = Path(__file__).resolve().parents[1]
SCENARIOS = ROOT / "tests" / "scenarios"
JSON_ARTIFACT = ROOT / "docs" / "DETECTION_VALIDATION_COVERAGE.json"
MARKDOWN_ARTIFACT = ROOT / "docs" / "DETECTION_VALIDATION_COVERAGE.md"
CODE_RULES = tuple(NIDS_RULES.values()) + tuple(CORRELATION_RULES.values())


class ValidationCoverageError(ValueError):
    pass


def _enabled_rules():
    native = load_rules(config.RULES_DIR, config.SIGNATURES)
    with tempfile.TemporaryDirectory(prefix="mini-siem-coverage-") as directory:
        sigma, _ = load_sigma_rules(
            config.SIGMA_RULES_DIR, str(Path(directory) / "sigma_rule_states.json")
        )
    rules = native + [rule for rule in sigma if rule["enabled"]] + list(CODE_RULES)
    ids = [rule["id"] for rule in rules]
    if len(ids) != len(set(ids)):
        raise ValidationCoverageError("enabled rule inventory contains duplicate IDs")
    return sorted(rules, key=lambda rule: rule["id"])


def build_validation_coverage():
    manifests = load_scenario_manifests(SCENARIOS)
    replay = replay_path(SCENARIOS)
    results = {item["scenario_id"]: item for item in replay["results"]}
    rules = _enabled_rules()
    inventory_ids = {rule["id"] for rule in rules}
    referenced_ids = {
        rule_id
        for manifest in manifests
        for rule_id in (
            manifest["expected"]["rule_ids"]
            + manifest.get("negative_expectations", {}).get("rule_ids", [])
        )
    }
    unknown = referenced_ids - inventory_ids
    if unknown:
        raise ValidationCoverageError(
            f"scenario corpus references unknown rule IDs: {', '.join(sorted(unknown))}"
        )

    matrix = []
    for rule in rules:
        rule_id = rule["id"]
        positive = sorted(
            manifest["id"] for manifest in manifests
            if rule_id in manifest["expected"]["rule_ids"]
        )
        negative = sorted(
            manifest["id"] for manifest in manifests
            if rule_id in manifest.get("negative_expectations", {}).get("rule_ids", [])
        )
        scenarios = sorted(set(positive + negative))
        passed = bool(positive) and all(
            results[scenario_id]["passed"]
            and (scenario_id not in positive or rule_id in results[scenario_id]["matched_rule_ids"])
            for scenario_id in scenarios
        )
        validation = "PASS" if passed else ("UNVALIDATED" if not positive else "FAIL")
        matrix.append({
            "rule_id": rule_id,
            "title": rule["title"],
            "enabled": True,
            "severity": rule["severity"],
            "source_type": rule["source_type"],
            "rule_source": rule.get("rule_source", "native"),
            "mitre_tactic": rule["mitre"]["tactic"],
            "mitre_technique": rule["mitre"]["technique"],
            "scenario_count": len(scenarios),
            "positive_scenarios": positive,
            "negative_scenarios": negative,
            "last_validation_result": validation,
            "runtime_hit_state": "NOT_EVALUATED",
            "runtime_hit_count": None,
        })

    status_counts = {
        status: sum(rule["last_validation_result"] == status for rule in matrix)
        for status in ("PASS", "FAIL", "UNVALIDATED")
    }
    return {
        "schema_version": 1,
        "summary": {
            "rules_total": len(matrix),
            "rules_validated": status_counts["PASS"],
            "rules_failed": status_counts["FAIL"],
            "rules_unvalidated": status_counts["UNVALIDATED"],
            "scenarios_total": replay["scenario_count"],
            "scenarios_passed": sum(result["passed"] for result in replay["results"]),
            "scenarios_failed": sum(not result["passed"] for result in replay["results"]),
            "runtime_hits_evaluated": False,
        },
        "rules": matrix,
    }


def json_artifact(report):
    return json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def markdown_artifact(report):
    summary = report["summary"]
    lines = [
        "# Detection Validation Coverage",
        "",
        "> Generated by `python tools/generate_validation_coverage.py`; do not edit manually.",
        "> Runtime hit counts are intentionally not read from the runtime database. A rule hit is not deterministic validation.",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Enabled rules | {summary['rules_total']} |",
        f"| Deterministically validated | {summary['rules_validated']} |",
        f"| Failed validation | {summary['rules_failed']} |",
        f"| Unvalidated enabled rules | {summary['rules_unvalidated']} |",
        f"| Passing scenarios | {summary['scenarios_passed']}/{summary['scenarios_total']} |",
        "| Runtime hit counts evaluated | No |",
        "",
        "## Rule matrix",
        "",
        "| Rule | Source | Severity | MITRE technique | Scenarios | Last validation result | Runtime hits |",
        "|---|---|:---:|---|---:|:---:|:---:|",
    ]
    for rule in report["rules"]:
        rule_label = f"{rule['rule_id']} — {rule['title']}".replace("|", "\\|")
        technique = f"{rule['mitre_technique']} ({rule['mitre_tactic']})".replace("|", "\\|")
        lines.append(
            f"| {rule_label} | {rule['rule_source']} / {rule['source_type']} | "
            f"{rule['severity']} | {technique} | {rule['scenario_count']} | "
            f"{rule['last_validation_result']} | Not evaluated |"
        )
    unvalidated = [
        rule for rule in report["rules"]
        if rule["last_validation_result"] == "UNVALIDATED"
    ]
    lines.extend(["", "## Unvalidated enabled rules", ""])
    lines.extend(
        [f"- `{rule['rule_id']}` — {rule['title']}" for rule in unvalidated]
        or ["None."]
    )
    lines.extend([
        "", "## Scenario mappings", "",
        "Positive scenarios prove a required rule match; negative scenarios prove the rule stays quiet.", "",
    ])
    for rule in report["rules"]:
        positive = ", ".join(f"`{item}`" for item in rule["positive_scenarios"]) or "None"
        negative = ", ".join(f"`{item}`" for item in rule["negative_scenarios"]) or "None"
        lines.append(f"- `{rule['rule_id']}` — positive: {positive}; negative: {negative}")
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate detection validation coverage")
    parser.add_argument("--check", action="store_true", help="Fail if committed artifacts are stale")
    args = parser.parse_args(argv)
    try:
        report = build_validation_coverage()
        artifacts = {
            JSON_ARTIFACT: json_artifact(report),
            MARKDOWN_ARTIFACT: markdown_artifact(report),
        }
        if args.check:
            stale = [
                path.name for path, content in artifacts.items()
                if not path.is_file() or path.read_text(encoding="utf-8") != content
            ]
            if stale:
                raise ValidationCoverageError(
                    f"stale validation coverage artifacts: {', '.join(stale)}"
                )
        else:
            for path, content in artifacts.items():
                path.write_text(content, encoding="utf-8")
    except (OSError, UnicodeError, ValueError) as exc:
        parser.exit(1, f"Coverage generation failed: {exc}\n")
    summary = report["summary"]
    print(
        f"Validation coverage: {summary['rules_validated']}/{summary['rules_total']} rules, "
        f"{summary['scenarios_passed']}/{summary['scenarios_total']} scenarios"
    )
    return 0 if summary["rules_failed"] == 0 and summary["scenarios_failed"] == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
